apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
    - name: echoserver
      image: brohitdev/express-hello-world:latest
      ports:
        - name: web-port
          containerPort: 6000
  restartPolicy: Always
